scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  _1d3be6cf832c40c9a02d8c705af843b0_on_table_1_at_verify_task_168:
    original_id: _1d3be6cf832c40c9a02d8c705af843b0
    category: figurine
    usd_path: ${MESATASK_USD_ROOT}/1d3be6cf832c40c9a02d8c705af843b0.usd
    usd_scale:
    - 66.22117298199095
    - 66.09482540929478
    - 66.27971645731623
    position:
    - -1.597995334382878
    - -1.2106299966387155
    - 0.8156785201677121
    size:
    - 0.17765605449676514
    - 0.28366708755493164
    - 0.10335724346805364
    detailed_caption: Figurine with a round base, textured surface, distinct facial features, limbs, clay
      material.
  _1d3be6cf832c40c9a02d8c705af843b0_on_table_2_at_verify_task_168:
    original_id: _1d3be6cf832c40c9a02d8c705af843b0
    category: figurine
    usd_path: ${MESATASK_USD_ROOT}/1d3be6cf832c40c9a02d8c705af843b0.usd
    usd_scale:
    - 66.22117298199095
    - 66.09482540929478
    - 66.27971645731623
    position:
    - -2.531145253624979
    - 2.682992432901721
    - 0.34166662212694066
    size:
    - 0.17765605449676514
    - 0.28366708755493164
    - 0.10335724346805364
    detailed_caption: Figurine with a round base, textured surface, distinct facial features, limbs, clay
      material.
  c8acdbc61406494680ac47700670ea22_on_table_2_at_verify_task_168:
    original_id: c8acdbc61406494680ac47700670ea22
    category: figurine
    usd_path: ${MESATASK_USD_ROOT}/c8acdbc61406494680ac47700670ea22.usd
    usd_scale:
    - 0.05480124271848954
    - 0.05468067300731272
    - 0.05479292006117666
    position:
    - -1.9606303788318817
    - 3.1386656324388738
    - 0.3339161430299282
    size:
    - 0.15329480171203613
    - 0.27294111251831055
    - 0.08785628527402878
    detailed_caption: Ceramic figurine with a round head, stylized features, textured surface, and warm
      colors.
  _0df095c0471b45c48f67baa440714e8d_on_table_2_at_verify_task_168:
    original_id: _0df095c0471b45c48f67baa440714e8d
    category: figurine
    usd_path: ${MESATASK_USD_ROOT}/0df095c0471b45c48f67baa440714e8d.usd
    usd_scale:
    - 3.179280676078348
    - 3.183207211636635
    - 3.1821521492704794
    position:
    - -2.1366895158318004
    - 2.609570312722506
    - 0.3679030680609867
    size:
    - 0.14583587646484375
    - 0.240814208984375
    - 0.15583013533614576
    detailed_caption: Ceramic cat figurine, smooth white with grey polka dots, cheerful expression, rounded
      body, curled tail.
episodes:
- benchmark_task_id: FODP/verify_task_168
  family: FODP
  task_id: verify_task_168
  episode_idx: 25
  original_idx: 168
  benchmark_instruction: Get the figurine with a round base, textured surface, distinct facial features,
    limbs, clay material from the table much smaller than another one and move it to white cabinet with
    grey bottle.
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Get the figurine with a round base, textured surface, distinct facial features, limbs,
    clay material from the table much smaller than another one and move it to white cabinet with grey
    bottle.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content:
      - _1d3be6cf832c40c9a02d8c705af843b0
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - _1d3be6cf832c40c9a02d8c705af843b0
      - c8acdbc61406494680ac47700670ea22
      - _0df095c0471b45c48f67baa440714e8d
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content:
      - _1d3be6cf832c40c9a02d8c705af843b0
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - c8acdbc61406494680ac47700670ea22
      - _0df095c0471b45c48f67baa440714e8d
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content:
      - _1d3be6cf832c40c9a02d8c705af843b0
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: table_2
  src_distractors:
  - table_1
  dest: cabinet_7
  dest_distractors:
  - cabinet_6
  - cabinet_8
  - cabinet_9
  - cabinet_10
  obj_meta:
    _1d3be6cf832c40c9a02d8c705af843b0:
      category: figurine
      detailed_caption: Figurine with a round base, textured surface, distinct facial features, limbs,
        clay material.
      usd_path: 1d3be6cf832c40c9a02d8c705af843b0.usd
      size:
      - 0.17765605449676514
      - 0.28366708755493164
      - 0.10335724346805364
  obj_distractors:
  - c8acdbc61406494680ac47700670ea22
  - _0df095c0471b45c48f67baa440714e8d
  obj_distractor_meta:
    c8acdbc61406494680ac47700670ea22:
      category: figurine
      detailed_caption: Ceramic figurine with a round head, stylized features, textured surface, and warm
        colors.
      usd_path: c8acdbc61406494680ac47700670ea22.usd
      size:
      - 0.15329480171203613
      - 0.27294111251831055
      - 0.08785628527402878
    _0df095c0471b45c48f67baa440714e8d:
      category: figurine
      detailed_caption: Ceramic cat figurine, smooth white with grey polka dots, cheerful expression,
        rounded body, curled tail.
      usd_path: 0df095c0471b45c48f67baa440714e8d.usd
      size:
      - 0.14583587646484375
      - 0.240814208984375
      - 0.15583013533614576
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: find
    args:
      target_category: figurine
      target_description: Figurine with a round base, textured surface, distinct facial features, limbs,
        clay material.
  - action: gaze_at
    args:
      target_category: figurine
      target_description: Figurine with a round base, textured surface, distinct facial features, limbs,
        clay material.
  - action: pick
    args:
      target_category: figurine
      target_description: Figurine with a round base, textured surface, distinct facial features, limbs,
        clay material.
  - action: nav_to
    args:
      receptacle_name: cabinet_10
  - action: nav_to
    args:
      receptacle_name: cabinet_9
  - action: nav_to
    args:
      receptacle_name: cabinet_6
  - action: nav_to
    args:
      receptacle_name: cabinet_7
  - action: place
    args:
      receptacle_name: cabinet_7
  placements:
    _1d3be6cf832c40c9a02d8c705af843b0_on_table_1_at_verify_task_168:
      position:
      - -1.597995334382878
      - -1.2106299966387155
      - 0.8156785201677121
      furniture: table_1
      original_id: _1d3be6cf832c40c9a02d8c705af843b0
    _1d3be6cf832c40c9a02d8c705af843b0_on_table_2_at_verify_task_168:
      position:
      - -2.531145253624979
      - 2.682992432901721
      - 0.34166662212694066
      furniture: table_2
      original_id: _1d3be6cf832c40c9a02d8c705af843b0
    c8acdbc61406494680ac47700670ea22_on_table_2_at_verify_task_168:
      position:
      - -1.9606303788318817
      - 3.1386656324388738
      - 0.3339161430299282
      furniture: table_2
      original_id: c8acdbc61406494680ac47700670ea22
    _0df095c0471b45c48f67baa440714e8d_on_table_2_at_verify_task_168:
      position:
      - -2.1366895158318004
      - 2.609570312722506
      - 0.3679030680609867
      furniture: table_2
      original_id: _0df095c0471b45c48f67baa440714e8d
  final_positions:
    _1d3be6cf832c40c9a02d8c705af843b0_on_table_1_at_verify_task_168:
      initial_pos:
      - -1.597995334382878
      - -1.2106299966387155
      - 0.9156785201677121
      final_pos:
      - -1.6190605163574219
      - -1.2028288841247559
      - 0.7877028584480286
      category: figurine
      original_id: _1d3be6cf832c40c9a02d8c705af843b0
    _1d3be6cf832c40c9a02d8c705af843b0_on_table_2_at_verify_task_168:
      initial_pos:
      - -2.531145253624979
      - 2.682992432901721
      - 0.44166662212694063
      final_pos:
      - -2.5519189834594727
      - 2.6851766109466553
      - 0.3136906325817108
      category: figurine
      original_id: _1d3be6cf832c40c9a02d8c705af843b0
    c8acdbc61406494680ac47700670ea22_on_table_2_at_verify_task_168:
      initial_pos:
      - -1.9606303788318817
      - 3.1386656324388738
      - 0.4339161430299282
      final_pos:
      - -1.8917244672775269
      - 3.1518452167510986
      - 0.3147282302379608
      category: figurine
      original_id: c8acdbc61406494680ac47700670ea22
    _0df095c0471b45c48f67baa440714e8d_on_table_2_at_verify_task_168:
      initial_pos:
      - -2.1366895158318004
      - 2.609570312722506
      - 0.4679030680609867
      final_pos:
      - -2.144333839416504
      - 2.652289628982544
      - 0.3046139180660248
      category: figurine
      original_id: _0df095c0471b45c48f67baa440714e8d
  global_index: 97
  target_object_id: _1d3be6cf832c40c9a02d8c705af843b0
