scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  _0ce234c918ef438c9c919848b137d7ba_on_table_1_at_verify_task_208:
    original_id: _0ce234c918ef438c9c919848b137d7ba
    category: teddy bear
    usd_path: ${MESATASK_USD_ROOT}/0ce234c918ef438c9c919848b137d7ba.usd
    usd_scale:
    - 0.21267695671131023
    - 0.2121924462983215
    - 0.2126520976650876
    position:
    - -2.174183721952543
    - -1.0843636868966113
    - 0.8315517467958853
    size:
    - 0.17091894149780273
    - 0.20502662658691406
    - 0.13510369672439992
    detailed_caption: Soft, plush teddy bear; rounded body, small ears, button-like eyes, light blue,
      fluffy surface.
  _0ce234c918ef438c9c919848b137d7ba_on_table_2_at_verify_task_208:
    original_id: _0ce234c918ef438c9c919848b137d7ba
    category: teddy bear
    usd_path: ${MESATASK_USD_ROOT}/0ce234c918ef438c9c919848b137d7ba.usd
    usd_scale:
    - 0.21267695671131023
    - 0.2121924462983215
    - 0.2126520976650876
    position:
    - -2.1142273622940584
    - 2.5030735254688175
    - 0.3575398487551138
    size:
    - 0.17091894149780273
    - 0.20502662658691406
    - 0.13510369672439992
    detailed_caption: Soft, plush teddy bear; rounded body, small ears, button-like eyes, light blue,
      fluffy surface.
episodes:
- task_id: verify_task_208
  episode_idx: 55
  original_idx: 208
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Navigate to the table to place my snack for watching TV, grasp the soft, plush teddy
    bear; rounded body, small ears, button-like eyes, light blue, fluffy surface, and carry it to the
    desk with black handle.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content:
      - _0ce234c918ef438c9c919848b137d7ba
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - _0ce234c918ef438c9c919848b137d7ba
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content:
      - _0ce234c918ef438c9c919848b137d7ba
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: table_2
  src_distractors:
  - table_1
  dest: desk_2
  dest_distractors:
  - desk_1
  obj_meta:
    _0ce234c918ef438c9c919848b137d7ba:
      category: teddy bear
      detailed_caption: Soft, plush teddy bear; rounded body, small ears, button-like eyes, light blue,
        fluffy surface.
      usd_path: 0ce234c918ef438c9c919848b137d7ba.usd
      size:
      - 0.17091894149780273
      - 0.20502662658691406
      - 0.13510369672439992
  obj_distractors:
  - c752c932af1a477a8fd37f6bb0ec5f64
  - _550c42a971ce4208867459ec96251eba
  obj_distractor_meta:
    c752c932af1a477a8fd37f6bb0ec5f64:
      category: teddy bear
      detailed_caption: Soft brown teddy bear with prominent ears, button eyes, light brown belly patch,
        round face.
      usd_path: c752c932af1a477a8fd37f6bb0ec5f64.usd
      size:
      - 0.2529454231262207
      - 0.30280303955078125
      - 0.20035326946526766
    _550c42a971ce4208867459ec96251eba:
      category: teddy bear
      detailed_caption: Soft, plush teddy bear with a rounded body, small limbs, circular belly patch,
        and large ears.
      usd_path: 550c42a971ce4208867459ec96251eba.usd
      size:
      - 0.1518557071685791
      - 0.18286705017089844
      - 0.11972041055560112
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: find
    args:
      target_category: teddy bear
      target_description: Soft, plush teddy bear; rounded body, small ears, button-like eyes, light blue,
        fluffy surface.
  - action: gaze_at
    args:
      target_category: teddy bear
      target_description: Soft, plush teddy bear; rounded body, small ears, button-like eyes, light blue,
        fluffy surface.
  - action: pick
    args:
      target_category: teddy bear
      target_description: Soft, plush teddy bear; rounded body, small ears, button-like eyes, light blue,
        fluffy surface.
  - action: nav_to
    args:
      receptacle_name: desk_2
  - action: place
    args:
      receptacle_name: desk_2
  placements:
    _0ce234c918ef438c9c919848b137d7ba_on_table_1_at_verify_task_208:
      position:
      - -2.174183721952543
      - -1.0843636868966113
      - 0.8315517467958853
      furniture: table_1
      original_id: _0ce234c918ef438c9c919848b137d7ba
    _0ce234c918ef438c9c919848b137d7ba_on_table_2_at_verify_task_208:
      position:
      - -2.1142273622940584
      - 2.5030735254688175
      - 0.3575398487551138
      furniture: table_2
      original_id: _0ce234c918ef438c9c919848b137d7ba
  final_positions:
    _0ce234c918ef438c9c919848b137d7ba_on_table_1_at_verify_task_208:
      initial_pos:
      - -2.174183721952543
      - -1.0843636868966113
      - 0.9315517467958853
      final_pos:
      - -2.1769344806671143
      - -1.0746911764144897
      - 0.8070247173309326
      category: teddy bear
      original_id: _0ce234c918ef438c9c919848b137d7ba
    _0ce234c918ef438c9c919848b137d7ba_on_table_2_at_verify_task_208:
      initial_pos:
      - -2.1142273622940584
      - 2.5030735254688175
      - 0.4575398487551138
      final_pos:
      - -2.1176178455352783
      - 2.51444935798645
      - 0.3330126404762268
      category: teddy bear
      original_id: _0ce234c918ef438c9c919848b137d7ba
  family: FDP
  benchmark_task_id: FDP/verify_task_208
  benchmark_instruction: Navigate to the table to place my snack for watching TV, grasp the soft, plush
    teddy bear; rounded body, small ears, button-like eyes, light blue, fluffy surface, and carry it to
    the desk with black handle.
  global_index: 55
  target_object_id: _0ce234c918ef438c9c919848b137d7ba
