scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  dfb60be05b914116b7178579e93516ed_on_table_1_at_verify_task_46:
    original_id: dfb60be05b914116b7178579e93516ed
    category: pen
    usd_path: ${MESATASK_USD_ROOT}/dfb60be05b914116b7178579e93516ed.usd
    usd_scale:
    - 0.018298897491465328
    - 0.01763507245730863
    - 0.018331101247054563
    position:
    - -2.3192607153535727
    - -1.5135501042135528
    - 0.7678793365880847
    size:
    - 0.12268638610839844
    - 0.06080317497253418
    - 0.00775887630879879
    detailed_caption: Cylindrical pen with a sleek, smooth, shiny exterior and decorative elements.
  dfb60be05b914116b7178579e93516ed_on_table_2_at_verify_task_46:
    original_id: dfb60be05b914116b7178579e93516ed
    category: pen
    usd_path: ${MESATASK_USD_ROOT}/dfb60be05b914116b7178579e93516ed.usd
    usd_scale:
    - 0.018298897491465328
    - 0.01763507245730863
    - 0.018331101247054563
    position:
    - -2.518590153622378
    - 2.6983188936485325
    - 0.29386743854731323
    size:
    - 0.12268638610839844
    - 0.06080317497253418
    - 0.00775887630879879
    detailed_caption: Cylindrical pen with a sleek, smooth, shiny exterior and decorative elements.
episodes:
- task_id: verify_task_46
  episode_idx: 27
  original_idx: 46
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Head over to the rectangular table, fetch the cylindrical pen with a sleek, smooth,
    shiny exterior and decorative elements, and bring it back to box table with circle insert.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content:
      - dfb60be05b914116b7178579e93516ed
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - dfb60be05b914116b7178579e93516ed
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content:
      - dfb60be05b914116b7178579e93516ed
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: table_1
  src_distractors:
  - table_2
  dest: cabinet_8
  dest_distractors:
  - cabinet_6
  - cabinet_7
  - cabinet_9
  - cabinet_10
  obj_meta:
    dfb60be05b914116b7178579e93516ed:
      category: pen
      detailed_caption: Cylindrical pen with a sleek, smooth, shiny exterior and decorative elements.
      usd_path: dfb60be05b914116b7178579e93516ed.usd
      size:
      - 0.12268638610839844
      - 0.06080317497253418
      - 0.00775887630879879
  obj_distractors:
  - gen_eccdb0db_bdc5_4acb_bd31_5e8ab87d299f
  - _1e305b5d90244f8ab23721d98150f425
  obj_distractor_meta:
    gen_eccdb0db_bdc5_4acb_bd31_5e8ab87d299f:
      category: notebook
      detailed_caption: Cylindrical pen holder with a textured surface, vibrant exterior, unique graphic
        designs, and sturdy base.
      usd_path: gen_eccdb0db-bdc5-4acb-bd31-5e8ab87d299f.usd
      size:
      - 0.0613250732421875
      - 0.13367462158203125
      - 0.05684599291998893
    _1e305b5d90244f8ab23721d98150f425:
      category: pen
      detailed_caption: Blue pen with turquoise cap and grip, sleek cylindrical shape, and fine tip.
      usd_path: 1e305b5d90244f8ab23721d98150f425.usd
      size:
      - 0.12883949279785156
      - 0.020580291748046875
      - 0.01236963868723251
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: find
    args:
      target_category: pen
      target_description: Cylindrical pen with a sleek, smooth, shiny exterior and decorative elements.
  - action: gaze_at
    args:
      target_category: pen
      target_description: Cylindrical pen with a sleek, smooth, shiny exterior and decorative elements.
  - action: pick
    args:
      target_category: pen
      target_description: Cylindrical pen with a sleek, smooth, shiny exterior and decorative elements.
  - action: nav_to
    args:
      receptacle_name: cabinet_7
  - action: nav_to
    args:
      receptacle_name: cabinet_9
  - action: nav_to
    args:
      receptacle_name: cabinet_8
  - action: place
    args:
      receptacle_name: cabinet_8
  placements:
    dfb60be05b914116b7178579e93516ed_on_table_1_at_verify_task_46:
      position:
      - -2.3192607153535727
      - -1.5135501042135528
      - 0.7678793365880847
      furniture: table_1
      original_id: dfb60be05b914116b7178579e93516ed
    dfb60be05b914116b7178579e93516ed_on_table_2_at_verify_task_46:
      position:
      - -2.518590153622378
      - 2.6983188936485325
      - 0.29386743854731323
      furniture: table_2
      original_id: dfb60be05b914116b7178579e93516ed
  final_positions:
    dfb60be05b914116b7178579e93516ed_on_table_1_at_verify_task_46:
      initial_pos:
      - -2.3192607153535727
      - -1.5135501042135528
      - 0.8678793365880847
      final_pos:
      - -2.2534806728363037
      - -1.5480598211288452
      - 0.7473320364952087
      category: pencil pen
      original_id: dfb60be05b914116b7178579e93516ed
    dfb60be05b914116b7178579e93516ed_on_table_2_at_verify_task_46:
      initial_pos:
      - -2.518590153622378
      - 2.6983188936485325
      - 0.3938674385473132
      final_pos:
      - -2.453234910964966
      - 2.6602942943573
      - 0.27325713634490967
      category: pencil pen
      original_id: dfb60be05b914116b7178579e93516ed
  family: FDP
  benchmark_task_id: FDP/verify_task_46
  benchmark_instruction: Head over to the rectangular table, fetch the cylindrical pen with a sleek, smooth,
    shiny exterior and decorative elements, and bring it back to box table with circle insert.
  global_index: 27
  target_object_id: dfb60be05b914116b7178579e93516ed
