scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  cf2b3e74a7b547e2a75dba0187584190_on_table_1_at_verify_task_32:
    original_id: cf2b3e74a7b547e2a75dba0187584190
    category: remote control
    usd_path: ${MESATASK_USD_ROOT}/cf2b3e74a7b547e2a75dba0187584190.usd
    usd_scale:
    - 0.15257246027027485
    - 0.15117129291725986
    - 0.14418062139125867
    position:
    - -2.291932316711991
    - -1.5515534507677833
    - 0.789098866803688
    size:
    - 0.22077178955078125
    - 0.225372314453125
    - 0.05019793674000539
    detailed_caption: Sleek black remote control, curved design, glossy surface, colored buttons, ergonomic
      grip.
  cf2b3e74a7b547e2a75dba0187584190_on_table_2_at_verify_task_32:
    original_id: cf2b3e74a7b547e2a75dba0187584190
    category: remote control
    usd_path: ${MESATASK_USD_ROOT}/cf2b3e74a7b547e2a75dba0187584190.usd
    usd_scale:
    - 0.15257246027027485
    - 0.15117129291725986
    - 0.14418062139125867
    position:
    - -1.8385059203454603
    - 2.573774748809618
    - 0.31508696876291653
    size:
    - 0.22077178955078125
    - 0.225372314453125
    - 0.05019793674000539
    detailed_caption: Sleek black remote control, curved design, glossy surface, colored buttons, ergonomic
      grip.
episodes:
- task_id: verify_task_32
  episode_idx: 22
  original_idx: 32
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Get the sleek black remote control, curved design, glossy surface, colored buttons,
    ergonomic grip from the table where we have dinner and move it to cabinet with drawers with orange
    inner backing.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content:
      - cf2b3e74a7b547e2a75dba0187584190
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - cf2b3e74a7b547e2a75dba0187584190
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content:
      - cf2b3e74a7b547e2a75dba0187584190
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: table_1
  src_distractors:
  - table_2
  dest: cabinet_6
  dest_distractors:
  - cabinet_7
  - cabinet_8
  - cabinet_9
  - cabinet_10
  obj_meta:
    cf2b3e74a7b547e2a75dba0187584190:
      category: remote control
      detailed_caption: Sleek black remote control, curved design, glossy surface, colored buttons, ergonomic
        grip.
      usd_path: cf2b3e74a7b547e2a75dba0187584190.usd
      size:
      - 0.22077178955078125
      - 0.225372314453125
      - 0.05019793674000539
  obj_distractors:
  - fc55a7410d674754a8963216cf728f80
  - _267f6fc623254562a150ee002f027179
  obj_distractor_meta:
    fc55a7410d674754a8963216cf728f80:
      category: remote control
      detailed_caption: Remote control, slim rectangular shape, smooth surface, primarily white with blue
        accents.
      usd_path: fc55a7410d674754a8963216cf728f80.usd
      size:
      - 0.05971384048461914
      - 0.00995635986328125
      - 0.21438525664075314
    _267f6fc623254562a150ee002f027179:
      category: remote control
      detailed_caption: Sleek black remote control with a circular navigation button and multicolored
        buttons. Compact design.
      usd_path: 267f6fc623254562a150ee002f027179.usd
      size:
      - 0.08344650268554688
      - 0.026447296142578125
      - 0.2352405652110292
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: find
    args:
      target_category: remote control
      target_description: Sleek black remote control, curved design, glossy surface, colored buttons,
        ergonomic grip.
  - action: gaze_at
    args:
      target_category: remote control
      target_description: Sleek black remote control, curved design, glossy surface, colored buttons,
        ergonomic grip.
  - action: pick
    args:
      target_category: remote control
      target_description: Sleek black remote control, curved design, glossy surface, colored buttons,
        ergonomic grip.
  - action: nav_to
    args:
      receptacle_name: cabinet_8
  - action: nav_to
    args:
      receptacle_name: cabinet_7
  - action: nav_to
    args:
      receptacle_name: cabinet_9
  - action: nav_to
    args:
      receptacle_name: cabinet_6
  - action: place
    args:
      receptacle_name: cabinet_6
  placements:
    cf2b3e74a7b547e2a75dba0187584190_on_table_1_at_verify_task_32:
      position:
      - -2.291932316711991
      - -1.5515534507677833
      - 0.789098866803688
      furniture: table_1
      original_id: cf2b3e74a7b547e2a75dba0187584190
    cf2b3e74a7b547e2a75dba0187584190_on_table_2_at_verify_task_32:
      position:
      - -1.8385059203454603
      - 2.573774748809618
      - 0.31508696876291653
      furniture: table_2
      original_id: cf2b3e74a7b547e2a75dba0187584190
  final_positions:
    cf2b3e74a7b547e2a75dba0187584190_on_table_1_at_verify_task_32:
      initial_pos:
      - -2.291932316711991
      - -1.5515534507677833
      - 0.889098866803688
      final_pos:
      - -2.3312036991119385
      - -1.3885899782180786
      - 0.7675444483757019
      category: remote control
      original_id: cf2b3e74a7b547e2a75dba0187584190
    cf2b3e74a7b547e2a75dba0187584190_on_table_2_at_verify_task_32:
      initial_pos:
      - -1.8385059203454603
      - 2.573774748809618
      - 0.4150869687629165
      final_pos:
      - -1.8322809934616089
      - 2.7760684490203857
      - 0.29150986671447754
      category: remote control
      original_id: cf2b3e74a7b547e2a75dba0187584190
  family: FDP
  benchmark_task_id: FDP/verify_task_32
  benchmark_instruction: Get the sleek black remote control, curved design, glossy surface, colored buttons,
    ergonomic grip from the table where we have dinner and move it to cabinet with drawers with orange
    inner backing.
  global_index: 22
  target_object_id: cf2b3e74a7b547e2a75dba0187584190
