scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  _79bff744c1b74462af7d3c0b9b19267b_on_table_1_at_verify_task_6:
    original_id: _79bff744c1b74462af7d3c0b9b19267b
    category: remote control
    usd_path: ${MESATASK_USD_ROOT}/79bff744c1b74462af7d3c0b9b19267b.usd
    usd_scale:
    - 2.2885093903977354
    - 2.4589316029923878
    - 2.4922745634304047
    position:
    - -2.534465344650064
    - -1.285177387508115
    - 0.7779798684164416
    size:
    - 0.08931159973144531
    - 0.224365234375
    - 0.027959939965512604
    detailed_caption: Sleek, rectangular remote control with a black body and large, brightly colored
      buttons.
  _79bff744c1b74462af7d3c0b9b19267b_on_table_2_at_verify_task_6:
    original_id: _79bff744c1b74462af7d3c0b9b19267b
    category: remote control
    usd_path: ${MESATASK_USD_ROOT}/79bff744c1b74462af7d3c0b9b19267b.usd
    usd_scale:
    - 2.2885093903977354
    - 2.4589316029923878
    - 2.4922745634304047
    position:
    - -1.8885603986545396
    - 2.611305949131838
    - 0.30396797037567014
    size:
    - 0.08931159973144531
    - 0.224365234375
    - 0.027959939965512604
    detailed_caption: Sleek, rectangular remote control with a black body and large, brightly colored
      buttons.
episodes:
- task_id: verify_task_6
  episode_idx: 2
  original_idx: 6
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Pick up the sleek, rectangular remote control with a black body and large, brightly
    colored buttons from the table to place my snack for watching TV and place it on the rectangular table.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content:
      - _79bff744c1b74462af7d3c0b9b19267b
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - _79bff744c1b74462af7d3c0b9b19267b
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content:
      - _79bff744c1b74462af7d3c0b9b19267b
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: table_2
  src_distractors:
  - table_1
  dest: table_1
  dest_distractors:
  - table_2
  obj_meta:
    _79bff744c1b74462af7d3c0b9b19267b:
      category: remote control
      detailed_caption: Sleek, rectangular remote control with a black body and large, brightly colored
        buttons.
      usd_path: 79bff744c1b74462af7d3c0b9b19267b.usd
      size:
      - 0.08931159973144531
      - 0.224365234375
      - 0.027959939965512604
  obj_distractors:
  - _267f6fc623254562a150ee002f027179
  - _37cecdef437e4f72ba5a0e9dafdf6bd5
  obj_distractor_meta:
    _267f6fc623254562a150ee002f027179:
      category: remote control
      detailed_caption: Sleek black remote control with a circular navigation button and multicolored
        buttons. Compact design.
      usd_path: 267f6fc623254562a150ee002f027179.usd
      size:
      - 0.08344650268554688
      - 0.026447296142578125
      - 0.2352405652110292
    _37cecdef437e4f72ba5a0e9dafdf6bd5:
      category: remote control
      detailed_caption: Remote control with a rectangular shape, smooth white surface, light gray accents,
        and digital display.
      usd_path: 37cecdef437e4f72ba5a0e9dafdf6bd5.usd
      size:
      - 0.056670188903808594
      - 0.03021240234375
      - 0.15303719168150565
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: find
    args:
      target_category: remote control
      target_description: Sleek, rectangular remote control with a black body and large, brightly colored
        buttons.
  - action: gaze_at
    args:
      target_category: remote control
      target_description: Sleek, rectangular remote control with a black body and large, brightly colored
        buttons.
  - action: pick
    args:
      target_category: remote control
      target_description: Sleek, rectangular remote control with a black body and large, brightly colored
        buttons.
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: place
    args:
      receptacle_name: table_1
  placements:
    _79bff744c1b74462af7d3c0b9b19267b_on_table_1_at_verify_task_6:
      position:
      - -2.534465344650064
      - -1.285177387508115
      - 0.7779798684164416
      furniture: table_1
      original_id: _79bff744c1b74462af7d3c0b9b19267b
    _79bff744c1b74462af7d3c0b9b19267b_on_table_2_at_verify_task_6:
      position:
      - -1.8885603986545396
      - 2.611305949131838
      - 0.30396797037567014
      furniture: table_2
      original_id: _79bff744c1b74462af7d3c0b9b19267b
  final_positions:
    _79bff744c1b74462af7d3c0b9b19267b_on_table_1_at_verify_task_6:
      initial_pos:
      - -2.534465344650064
      - -1.285177387508115
      - 0.8779798684164416
      final_pos:
      - -2.521096706390381
      - -1.1554741859436035
      - 0.7572895288467407
      category: remote control
      original_id: _79bff744c1b74462af7d3c0b9b19267b
    _79bff744c1b74462af7d3c0b9b19267b_on_table_2_at_verify_task_6:
      initial_pos:
      - -1.8885603986545396
      - 2.611305949131838
      - 0.4039679703756701
      final_pos:
      - -1.8842225074768066
      - 2.7396624088287354
      - 0.28327757120132446
      category: remote control
      original_id: _79bff744c1b74462af7d3c0b9b19267b
  family: FDP
  benchmark_task_id: FDP/verify_task_6
  benchmark_instruction: Pick up the sleek, rectangular remote control with a black body and large, brightly
    colored buttons from the table to place my snack for watching TV and place it on the rectangular table.
  global_index: 2
  target_object_id: _79bff744c1b74462af7d3c0b9b19267b
