scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  _0f27ac8853b7498892751acef48299cc_on_bed_1_at_verify_task_180:
    original_id: _0f27ac8853b7498892751acef48299cc
    category: teddy bear
    usd_path: ${MESATASK_USD_ROOT}/0f27ac8853b7498892751acef48299cc.usd
    usd_scale:
    - 4.16056920184218
    - 4.166486136256042
    - 4.168626917344152
    position:
    - 3.6653584530683987
    - 3.435145494054643
    - 0.6041678845463321
    size:
    - 0.3871042728424072
    - 0.4038982391357422
    - 0.2237654661294073
    detailed_caption: A teddy bear figure with a round body, outstretched arms, light brown color, smooth
      texture.
  _0f27ac8853b7498892751acef48299cc_on_bed_2_at_verify_task_180:
    original_id: _0f27ac8853b7498892751acef48299cc
    category: teddy bear
    usd_path: ${MESATASK_USD_ROOT}/0f27ac8853b7498892751acef48299cc.usd
    usd_scale:
    - 4.16056920184218
    - 4.166486136256042
    - 4.168626917344152
    position:
    - 4.619651445086019
    - -1.633391395433407
    - 0.6340319573460147
    size:
    - 0.3871042728424072
    - 0.4038982391357422
    - 0.2237654661294073
    detailed_caption: A teddy bear figure with a round body, outstretched arms, light brown color, smooth
      texture.
episodes:
- task_id: verify_task_180
  episode_idx: 37
  original_idx: 180
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Transport the a teddy bear figure with a round body, outstretched arms, light brown
    color, smooth texture at bed with all-white bed sheet to the table to place my snack for watching
    TV.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content:
      - _0f27ac8853b7498892751acef48299cc
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content:
      - _0f27ac8853b7498892751acef48299cc
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content:
      - _0f27ac8853b7498892751acef48299cc
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: bed_1
  src_distractors:
  - bed_2
  dest: table_2
  dest_distractors:
  - table_1
  obj_meta:
    _0f27ac8853b7498892751acef48299cc:
      category: teddy bear
      detailed_caption: A teddy bear figure with a round body, outstretched arms, light brown color, smooth
        texture.
      usd_path: 0f27ac8853b7498892751acef48299cc.usd
      size:
      - 0.3871042728424072
      - 0.4038982391357422
      - 0.2237654661294073
  obj_distractors:
  - _3ab5f94d4f3745a48c7b8e5023836f8e
  - _550c42a971ce4208867459ec96251eba
  obj_distractor_meta:
    _3ab5f94d4f3745a48c7b8e5023836f8e:
      category: teddy bear
      detailed_caption: A teddy bear with soft fur, small wings, round belly, and button-like eyes.
      usd_path: 3ab5f94d4f3745a48c7b8e5023836f8e.usd
      size:
      - 0.17863845825195312
      - 0.19546127319335938
      - 0.1770838350057602
    _550c42a971ce4208867459ec96251eba:
      category: teddy bear
      detailed_caption: Soft, plush teddy bear with a rounded body, small limbs, circular belly patch,
        and large ears.
      usd_path: 550c42a971ce4208867459ec96251eba.usd
      size:
      - 0.1518557071685791
      - 0.18286705017089844
      - 0.11972041055560112
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: bed_1
  - action: find
    args:
      target_category: teddy bear
      target_description: A teddy bear figure with a round body, outstretched arms, light brown color,
        smooth texture.
  - action: gaze_at
    args:
      target_category: teddy bear
      target_description: A teddy bear figure with a round body, outstretched arms, light brown color,
        smooth texture.
  - action: pick
    args:
      target_category: teddy bear
      target_description: A teddy bear figure with a round body, outstretched arms, light brown color,
        smooth texture.
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: place
    args:
      receptacle_name: table_2
  placements:
    _0f27ac8853b7498892751acef48299cc_on_bed_1_at_verify_task_180:
      position:
      - 3.6653584530683987
      - 3.435145494054643
      - 0.6041678845463321
      furniture: bed_1
      original_id: _0f27ac8853b7498892751acef48299cc
    _0f27ac8853b7498892751acef48299cc_on_bed_2_at_verify_task_180:
      position:
      - 4.619651445086019
      - -1.633391395433407
      - 0.6340319573460147
      furniture: bed_2
      original_id: _0f27ac8853b7498892751acef48299cc
  final_positions:
    _0f27ac8853b7498892751acef48299cc_on_bed_1_at_verify_task_180:
      initial_pos:
      - 3.6653584530683987
      - 3.435145494054643
      - 0.7041678845463321
      final_pos:
      - 3.6655311584472656
      - 3.3854851722717285
      - 0.5634023547172546
      category: teddy bear
      original_id: _0f27ac8853b7498892751acef48299cc
    _0f27ac8853b7498892751acef48299cc_on_bed_2_at_verify_task_180:
      initial_pos:
      - 4.619651445086019
      - -1.633391395433407
      - 0.7340319573460147
      final_pos:
      - 4.18027925491333
      - -1.519230604171753
      - 0.6057677268981934
      category: teddy bear
      original_id: _0f27ac8853b7498892751acef48299cc
  family: FDP
  benchmark_task_id: FDP/verify_task_180
  benchmark_instruction: Transport the a teddy bear figure with a round body, outstretched arms, light
    brown color, smooth texture at bed with all-white bed sheet to the table to place my snack for watching
    TV.
  global_index: 37
  target_object_id: _0f27ac8853b7498892751acef48299cc
