scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  a51ba478_3a52_4f69_a08b_80032e52345f_on_desk_1_at_verify_task_41:
    original_id: a51ba478_3a52_4f69_a08b_80032e52345f
    category: pen
    usd_path: ${MESATASK_USD_ROOT}/a51ba478-3a52-4f69-a08b-80032e52345f.usd
    usd_scale:
    - 6.77896498902569
    - 6.819060092291459
    - 7.737536068802587
    position:
    - 0.12343160160300859
    - -2.900058146415318
    - 0.7630495050939499
    size:
    - 0.00919342041015625
    - 0.1358642578125
    - 0.01009893961600028
    detailed_caption: Red cylindrical felt-tip pen with a fine tip, white clip, and transparent ink level
      end.
  c2d225488fe84a0ab451717100132495_on_desk_1_at_verify_task_41:
    original_id: c2d225488fe84a0ab451717100132495
    category: marker
    usd_path: ${MESATASK_USD_ROOT}/c2d225488fe84a0ab451717100132495.usd
    usd_scale:
    - 3.543353513625197
    - 3.5433554379739
    - 3.568540801108354
    position:
    - -0.16320159696630465
    - -2.57991240263292
    - 0.794955187458545
    size:
    - 0.07042312622070312
    - 0.15536999702453613
    - 0.07391030434519053
    detailed_caption: Cylindrical can with a vibrant green exterior, printed label, and graphic of a cat.
  a2771221af4c434281a35fd3a69778e6_on_desk_1_at_verify_task_41:
    original_id: a2771221af4c434281a35fd3a69778e6
    category: pencil
    usd_path: ${MESATASK_USD_ROOT}/a2771221af4c434281a35fd3a69778e6.usd
    usd_scale:
    - 1.3128232882026665
    - 1.3121319086058225
    - 1.3285054599295505
    position:
    - -0.08144200799559101
    - -2.8111579603638006
    - 0.7648839952048729
    size:
    - 0.1632847785949707
    - 0.008113861083984375
    - 0.01376791983784642
    detailed_caption: Slender yellow hexagonal pencil with a sharpened tip and pink eraser at the end.
episodes:
- task_id: verify_task_41
  episode_idx: 31
  original_idx: 41
  benchmark_instruction: Head over to white desk in front of a picture, fetch a writing instrument, and
    bring it back to the table where we have dinner.
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Take the red cylindrical felt-tip pen with a fine tip, white clip, and transparent
    ink level end from white desk in front of a picture and put it on the table where we have dinner.
  fuzzy_task_description: Head over to white desk in front of a picture, fetch a writing instrument, and
    bring it back to the table where we have dinner.
  purpose: writing instrument
  purpose_group: writing_instruments
  initial_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content:
      - a51ba478_3a52_4f69_a08b_80032e52345f
      - c2d225488fe84a0ab451717100132495
      - a2771221af4c434281a35fd3a69778e6
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content:
      - a51ba478_3a52_4f69_a08b_80032e52345f
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content:
      - c2d225488fe84a0ab451717100132495
      - a2771221af4c434281a35fd3a69778e6
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: desk_1
  src_distractors:
  - desk_2
  dest: table_1
  dest_distractors:
  - table_2
  obj_meta:
    a51ba478_3a52_4f69_a08b_80032e52345f:
      category: pen
      detailed_caption: Red cylindrical felt-tip pen with a fine tip, white clip, and transparent ink
        level end.
      usd_path: a51ba478-3a52-4f69-a08b-80032e52345f.usd
      size:
      - 0.00919342041015625
      - 0.1358642578125
      - 0.01009893961600028
  obj_distractors:
  - c2d225488fe84a0ab451717100132495
  - a2771221af4c434281a35fd3a69778e6
  obj_distractor_meta:
    c2d225488fe84a0ab451717100132495:
      category: marker
      detailed_caption: Cylindrical can with a vibrant green exterior, printed label, and graphic of a
        cat.
      usd_path: c2d225488fe84a0ab451717100132495.usd
      size:
      - 0.07042312622070312
      - 0.15536999702453613
      - 0.07391030434519053
    a2771221af4c434281a35fd3a69778e6:
      category: pencil
      detailed_caption: Slender yellow hexagonal pencil with a sharpened tip and pink eraser at the end.
      usd_path: a2771221af4c434281a35fd3a69778e6.usd
      size:
      - 0.1632847785949707
      - 0.008113861083984375
      - 0.01376791983784642
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: desk_1
  - action: find
    args:
      target_category: pen
      target_description: Red cylindrical felt-tip pen with a fine tip, white clip, and transparent ink
        level end.
  - action: gaze_at
    args:
      target_category: pen
      target_description: Red cylindrical felt-tip pen with a fine tip, white clip, and transparent ink
        level end.
  - action: pick
    args:
      target_category: pen
      target_description: Red cylindrical felt-tip pen with a fine tip, white clip, and transparent ink
        level end.
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: place
    args:
      receptacle_name: table_1
  physics_task_description: Take the red cylindrical felt-tip pen with a fine tip, white clip, and transparent
    ink level end from white desk in front of a picture and put it on the table where we have dinner.
  placements:
    a51ba478_3a52_4f69_a08b_80032e52345f_on_desk_1_at_verify_task_41:
      position:
      - 0.12343160160300859
      - -2.900058146415318
      - 0.7630495050939499
      furniture: desk_1
      original_id: a51ba478_3a52_4f69_a08b_80032e52345f
    c2d225488fe84a0ab451717100132495_on_desk_1_at_verify_task_41:
      position:
      - -0.16320159696630465
      - -2.57991240263292
      - 0.794955187458545
      furniture: desk_1
      original_id: c2d225488fe84a0ab451717100132495
    a2771221af4c434281a35fd3a69778e6_on_desk_1_at_verify_task_41:
      position:
      - -0.08144200799559101
      - -2.8111579603638006
      - 0.7648839952048729
      furniture: desk_1
      original_id: a2771221af4c434281a35fd3a69778e6
  final_positions:
    a51ba478_3a52_4f69_a08b_80032e52345f_on_desk_1_at_verify_task_41:
      initial_pos:
      - 0.12343160160300859
      - -2.900058146415318
      - 0.8630495050939498
      final_pos:
      - 0.12858164310455322
      - -2.8999099731445312
      - 0.7418479323387146
      category: pen
      original_id: a51ba478_3a52_4f69_a08b_80032e52345f
    c2d225488fe84a0ab451717100132495_on_desk_1_at_verify_task_41:
      initial_pos:
      - -0.16320159696630465
      - -2.57991240263292
      - 0.894955187458545
      final_pos:
      - -0.1694371998310089
      - -2.5809812545776367
      - 0.7715394496917725
      category: marker
      original_id: c2d225488fe84a0ab451717100132495
    a2771221af4c434281a35fd3a69778e6_on_desk_1_at_verify_task_41:
      initial_pos:
      - -0.08144200799559101
      - -2.8111579603638006
      - 0.8648839952048729
      final_pos:
      - -0.08144279569387436
      - -2.810556650161743
      - 0.744697630405426
      category: pencil
      original_id: a2771221af4c434281a35fd3a69778e6
  family: SUL
  benchmark_task_id: SUL/verify_task_41
  global_index: 207
  target_object_id: a51ba478_3a52_4f69_a08b_80032e52345f
