scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  ca13bdd67bb14e0a9f9579ae3152d1d3_on_table_1_at_verify_task_28:
    original_id: ca13bdd67bb14e0a9f9579ae3152d1d3
    category: pen
    usd_path: ${MESATASK_USD_ROOT}/ca13bdd67bb14e0a9f9579ae3152d1d3.usd
    usd_scale:
    - 1.439434700765824
    - 1.415398485116941
    - 1.4961662834086935
    position:
    - -1.8777129080015225
    - -1.1790861228309486
    - 0.7689557806184166
    size:
    - 0.12482070922851562
    - 0.0071048736572265625
    - 0.009911764369462617
    detailed_caption: A ballpoint pen with a sleek design, blue tip, and wooden body.
  _2d1f086ba9064fc59c6c2ea757f4f576_on_table_1_at_verify_task_28:
    original_id: _2d1f086ba9064fc59c6c2ea757f4f576
    category: stylus
    usd_path: ${MESATASK_USD_ROOT}/2d1f086ba9064fc59c6c2ea757f4f576.usd
    usd_scale:
    - 3.524507489059508
    - 3.5091458113054723
    - 3.53251438805949
    position:
    - -2.300559744014223
    - -1.540499303467813
    - 0.8931041825526518
    size:
    - 0.039501190185546875
    - 0.037746429443359375
    - 0.2582085682379329
    detailed_caption: Sleek, futuristic pen or stylus, silver and black finish, rounded tip, ergonomic
      design.
  c2d225488fe84a0ab451717100132495_on_table_1_at_verify_task_28:
    original_id: c2d225488fe84a0ab451717100132495
    category: marker
    usd_path: ${MESATASK_USD_ROOT}/c2d225488fe84a0ab451717100132495.usd
    usd_scale:
    - 3.543353513625197
    - 3.5433554379739
    - 3.568540801108354
    position:
    - -1.5713562855945409
    - -1.3728101966629298
    - 0.8009550506062806
    size:
    - 0.07042312622070312
    - 0.15536999702453613
    - 0.07391030434519053
    detailed_caption: Cylindrical can with a vibrant green exterior, printed label, and graphic of a cat.
episodes:
- task_id: verify_task_28
  episode_idx: 23
  original_idx: 28
  benchmark_instruction: Take a writing instrument from the rectangular table and put it on wide desk
    with orange drawer pulls.
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_description: Retrieve the a ballpoint pen with a sleek design, blue tip, and wooden body from the
    rectangular table and deposit it at wide desk with orange drawer pulls.
  fuzzy_task_description: Take a writing instrument from the rectangular table and put it on wide desk
    with orange drawer pulls.
  purpose: writing instrument
  purpose_group: writing_instruments
  initial_world_graph:
    table_1:
      room: dinning room/0
      content:
      - ca13bdd67bb14e0a9f9579ae3152d1d3
      - _2d1f086ba9064fc59c6c2ea757f4f576
      - c2d225488fe84a0ab451717100132495
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  goal_world_graph:
    table_1:
      room: dinning room/0
      content:
      - _2d1f086ba9064fc59c6c2ea757f4f576
      - c2d225488fe84a0ab451717100132495
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content:
      - ca13bdd67bb14e0a9f9579ae3152d1d3
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
  src: table_1
  src_distractors:
  - table_2
  dest: desk_1
  dest_distractors:
  - desk_2
  obj_meta:
    ca13bdd67bb14e0a9f9579ae3152d1d3:
      category: pen
      detailed_caption: A ballpoint pen with a sleek design, blue tip, and wooden body.
      usd_path: ca13bdd67bb14e0a9f9579ae3152d1d3.usd
      size:
      - 0.12482070922851562
      - 0.0071048736572265625
      - 0.009911764369462617
  obj_distractors:
  - _2d1f086ba9064fc59c6c2ea757f4f576
  - c2d225488fe84a0ab451717100132495
  obj_distractor_meta:
    _2d1f086ba9064fc59c6c2ea757f4f576:
      category: stylus
      detailed_caption: Sleek, futuristic pen or stylus, silver and black finish, rounded tip, ergonomic
        design.
      usd_path: 2d1f086ba9064fc59c6c2ea757f4f576.usd
      size:
      - 0.039501190185546875
      - 0.037746429443359375
      - 0.2582085682379329
    c2d225488fe84a0ab451717100132495:
      category: marker
      detailed_caption: Cylindrical can with a vibrant green exterior, printed label, and graphic of a
        cat.
      usd_path: c2d225488fe84a0ab451717100132495.usd
      size:
      - 0.07042312622070312
      - 0.15536999702453613
      - 0.07391030434519053
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: table_2
  - action: nav_to
    args:
      receptacle_name: table_1
  - action: find
    args:
      target_category: pen
      target_description: A ballpoint pen with a sleek design, blue tip, and wooden body.
  - action: gaze_at
    args:
      target_category: pen
      target_description: A ballpoint pen with a sleek design, blue tip, and wooden body.
  - action: pick
    args:
      target_category: pen
      target_description: A ballpoint pen with a sleek design, blue tip, and wooden body.
  - action: nav_to
    args:
      receptacle_name: desk_2
  - action: nav_to
    args:
      receptacle_name: desk_1
  - action: place
    args:
      receptacle_name: desk_1
  physics_task_description: Retrieve the a ballpoint pen with a sleek design, blue tip, and wooden body
    from the rectangular table and deposit it at wide desk with orange drawer pulls.
  placements:
    ca13bdd67bb14e0a9f9579ae3152d1d3_on_table_1_at_verify_task_28:
      position:
      - -1.8777129080015225
      - -1.1790861228309486
      - 0.7689557806184166
      furniture: table_1
      original_id: ca13bdd67bb14e0a9f9579ae3152d1d3
    _2d1f086ba9064fc59c6c2ea757f4f576_on_table_1_at_verify_task_28:
      position:
      - -2.300559744014223
      - -1.540499303467813
      - 0.8931041825526518
      furniture: table_1
      original_id: _2d1f086ba9064fc59c6c2ea757f4f576
    c2d225488fe84a0ab451717100132495_on_table_1_at_verify_task_28:
      position:
      - -1.5713562855945409
      - -1.3728101966629298
      - 0.8009550506062806
      furniture: table_1
      original_id: c2d225488fe84a0ab451717100132495
  final_positions:
    ca13bdd67bb14e0a9f9579ae3152d1d3_on_table_1_at_verify_task_28:
      initial_pos:
      - -1.8777129080015225
      - -1.1790861228309486
      - 0.8689557806184166
      final_pos:
      - -1.806976556777954
      - -1.1780136823654175
      - 0.7477374076843262
      category: pen
      original_id: ca13bdd67bb14e0a9f9579ae3152d1d3
    _2d1f086ba9064fc59c6c2ea757f4f576_on_table_1_at_verify_task_28:
      initial_pos:
      - -2.300559744014223
      - -1.540499303467813
      - 0.9931041825526518
      final_pos:
      - -2.3012101650238037
      - -1.690804123878479
      - 0.7625142931938171
      category: stylus
      original_id: _2d1f086ba9064fc59c6c2ea757f4f576
    c2d225488fe84a0ab451717100132495_on_table_1_at_verify_task_28:
      initial_pos:
      - -1.5713562855945409
      - -1.3728101966629298
      - 0.9009550506062806
      final_pos:
      - -1.5777242183685303
      - -1.3737690448760986
      - 0.7775395512580872
      category: marker
      original_id: c2d225488fe84a0ab451717100132495
  family: SUL
  benchmark_task_id: SUL/verify_task_28
  global_index: 199
  target_object_id: ca13bdd67bb14e0a9f9579ae3152d1d3
