scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  _73bded78b3f64a4891721002c8653424_on_bed_1_at_verify_task_107:
    original_id: _73bded78b3f64a4891721002c8653424
    category: bun
    usd_path: ${MESATASK_USD_ROOT}/73bded78b3f64a4891721002c8653424.usd
    usd_scale:
    - 1.5384582154601065
    - 1.537833667893454
    - 1.5463744024783683
    position:
    - 3.6332053718711173
    - 4.073448074602057
    - 0.5357798014115542
    size:
    - 0.12386894226074219
    - 0.11658096313476562
    - 0.0869892998598516
  _73bded78b3f64a4891721002c8653424_on_bed_2_at_verify_task_107:
    original_id: _73bded78b3f64a4891721002c8653424
    category: bun
    usd_path: ${MESATASK_USD_ROOT}/73bded78b3f64a4891721002c8653424.usd
    usd_scale:
    - 1.5384582154601065
    - 1.537833667893454
    - 1.5463744024783683
    position:
    - 4.920600336151146
    - -1.9099804372278113
    - 0.5656438742112369
    size:
    - 0.12386894226074219
    - 0.11658096313476562
    - 0.0869892998598516
episodes:
- benchmark_task_id: FDO/verify_task_107
  family: FDO
  task_id: verify_task_107
  episode_idx: 20
  original_idx: 107
  benchmark_instruction: Navigate to bed with dark satin bedding, grasp a bun, and carry it to the only
    electriccooker in the scene.
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_type: store
  task_description: Navigate to bed with dark satin bedding, grasp a bun, and carry it to the only electriccooker
    in the scene.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    washingmachine_1:
      room: washingroom/0
      content: []
      door: false
    bed_1:
      room: bedroom/0
      content:
      - _73bded78b3f64a4891721002c8653424
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content:
      - _73bded78b3f64a4891721002c8653424
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
    electriccooker_0:
      room: kitchen/0
      content: []
      door: false
  goal_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    washingmachine_1:
      room: washingroom/0
      content: []
      door: false
    bed_1:
      room: bedroom/0
      content:
      - _73bded78b3f64a4891721002c8653424
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
    electriccooker_0:
      room: kitchen/0
      content:
      - _73bded78b3f64a4891721002c8653424
      door: false
  src: bed_2
  src_distractors:
  - bed_1
  dest: electriccooker_0
  dest_distractors: []
  obj_meta:
    _73bded78b3f64a4891721002c8653424:
      category: bun
      usd_path: 73bded78b3f64a4891721002c8653424.usd
      size:
      - 0.12386894226074219
      - 0.11658096313476562
      - 0.0869892998598516
  obj_distractors: []
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: electriccooker_0
  - action: open
    args:
      receptacle_name: electriccooker_0
  - action: nav_to
    args:
      receptacle_name: bed_2
  - action: find
    args:
      target_category: bun
  - action: gaze_at
    args:
      target_category: bun
  - action: pick
    args:
      target_category: bun
  - action: nav_to
    args:
      receptacle_name: electriccooker_0
  - action: place
    args:
      receptacle_name: electriccooker_0
  - action: close
    args:
      receptacle_name: electriccooker_0
  placements:
    _73bded78b3f64a4891721002c8653424_on_bed_1_at_verify_task_107:
      position:
      - 3.6332053718711173
      - 4.073448074602057
      - 0.5357798014115542
      furniture: bed_1
      original_id: _73bded78b3f64a4891721002c8653424
    _73bded78b3f64a4891721002c8653424_on_bed_2_at_verify_task_107:
      position:
      - 4.920600336151146
      - -1.9099804372278113
      - 0.5656438742112369
      furniture: bed_2
      original_id: _73bded78b3f64a4891721002c8653424
  final_positions:
    _73bded78b3f64a4891721002c8653424_on_bed_1_at_verify_task_107:
      initial_pos:
      - 3.6332053718711173
      - 4.073448074602057
      - 0.6357798014115542
      final_pos:
      - 3.6256229877471924
      - 4.114591598510742
      - 0.48983481526374817
      category: bun
      original_id: _73bded78b3f64a4891721002c8653424
    _73bded78b3f64a4891721002c8653424_on_bed_2_at_verify_task_107:
      initial_pos:
      - 4.920600336151146
      - -1.9099804372278113
      - 0.6656438742112368
      final_pos:
      - 5.013810634613037
      - -1.8191829919815063
      - 0.5438101887702942
      category: bun
      original_id: _73bded78b3f64a4891721002c8653424
  global_index: 148
  target_object_id: _73bded78b3f64a4891721002c8653424
