scene_id: MVUCSQAKTKJ5EAABAAAAABY8
paths:
  scene_usd: assets/scenes/MVUCSQAKTKJ5EAABAAAAABY8_usd/scene.usd
  occ_map_dir: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8
  furniture_lib: assets/metadata/MVUCSQAKTKJ5EAABAAAAABY8/scene_furniture_library.json
objects:
  f54556a921e4469ca05e3be621be8254_on_pot_0_at_verify_task_151:
    original_id: f54556a921e4469ca05e3be621be8254
    category: peanut
    usd_path: ${MESATASK_USD_ROOT}/f54556a921e4469ca05e3be621be8254.usd
    usd_scale:
    - 7.255964678767448
    - 7.196830443673207
    - 7.227198613878211
    position:
    - -5.189171424323978
    - -5.62657085864377
    - 1.004543590573594
    size:
    - 0.1145782470703125
    - 0.11831283569335938
    - 0.0534604168497026
episodes:
- benchmark_task_id: FDO/verify_task_151
  family: FDO
  task_id: verify_task_151
  episode_idx: 34
  original_idx: 151
  benchmark_instruction: Head over to the pot on the stove, fetch a peanut, and bring it back to the washingmachine.
  scene_id: MVUCSQAKTKJ5EAABAAAAABY8
  task_type: store
  task_description: Head over to the pot on the stove, fetch a peanut, and bring it back to the washingmachine.
  initial_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    washingmachine_1:
      room: washingroom/0
      content: []
      door: false
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content:
      - f54556a921e4469ca05e3be621be8254
    electriccooker_0:
      room: kitchen/0
      content: []
      door: false
  goal_world_graph:
    table_1:
      room: dinning room/0
      content: []
    couch_2:
      room: living room/0
      content: []
    table_2:
      room: living room/0
      content: []
    desk_1:
      room: study room/0
      content: []
    cabinet_6:
      room: study room/0
      content: []
    cabinet_7:
      room: washingroom/0
      content: []
    washingmachine_1:
      room: washingroom/0
      content:
      - f54556a921e4469ca05e3be621be8254
      door: false
    bed_1:
      room: bedroom/0
      content: []
    cabinet_8:
      room: bedroom/0
      content: []
    desk_2:
      room: bedroom/0
      content: []
    cabinet_9:
      room: bedroom/1
      content: []
    bed_2:
      room: bedroom/1
      content: []
    cabinet_10:
      room: bedroom/1
      content: []
    sink_0:
      room: kitchen/0
      content: []
    sink_1:
      room: washingroom/0
      content: []
    potlid_0:
      room: kitchen/0
      content: []
    pot_0:
      room: kitchen/0
      content: []
    electriccooker_0:
      room: kitchen/0
      content: []
      door: false
  src: pot_0
  src_distractors: []
  dest: washingmachine_1
  dest_distractors: []
  obj_meta:
    f54556a921e4469ca05e3be621be8254:
      category: peanut
      usd_path: f54556a921e4469ca05e3be621be8254.usd
      size:
      - 0.1145782470703125
      - 0.11831283569335938
      - 0.0534604168497026
  obj_distractors: []
  execution_plan:
  - action: nav_to
    args:
      receptacle_name: washingmachine_1
  - action: open
    args:
      receptacle_name: washingmachine_1
  - action: nav_to
    args:
      receptacle_name: pot_0
  - action: find
    args:
      target_category: peanut
  - action: gaze_at
    args:
      target_category: peanut
  - action: pick
    args:
      target_category: peanut
  - action: nav_to
    args:
      receptacle_name: washingmachine_1
  - action: place
    args:
      receptacle_name: washingmachine_1
  - action: close
    args:
      receptacle_name: washingmachine_1
  placements:
    f54556a921e4469ca05e3be621be8254_on_pot_0_at_verify_task_151:
      position:
      - -5.189171424323978
      - -5.62657085864377
      - 1.004543590573594
      furniture: pot_0
      original_id: f54556a921e4469ca05e3be621be8254
  final_positions:
    f54556a921e4469ca05e3be621be8254_on_pot_0_at_verify_task_151:
      initial_pos:
      - -5.189171424323978
      - -5.62657085864377
      - 1.104543590573594
      final_pos:
      - -5.1017045974731445
      - -5.668867588043213
      - 0.8878570199012756
      category: peanut
      original_id: f54556a921e4469ca05e3be621be8254
  global_index: 162
  target_object_id: f54556a921e4469ca05e3be621be8254
